Add unit test for the fix by issue #351 (fixes #355)
openmeteo/enhydris pull request #356
Opened 2020-10-14 12:16 UTC by eyobofficial

Closes #355

2020-10-15 06:04 UTC, aptiko requested changes
This unit test is very easy to break. If we change the message, it's almost certain we'll forget to change the unit test, and it will always be succeeding regardless whether the thing it's supposed to be testing works or not.

I think it would be better to change it with `assertContains(self.response, "Something that only exists when there's data")`.

2020-10-15 12:02 UTC, eyobofficial commented
@aptiko I am not exactly confident if my updated changes are also the right approach for the unit tests. So if you think this should also be changed (such as removing the HTML class & id names from the tests), let me know your comment on your feedback.

2020-10-15 13:44 UTC, aptiko requested changes

2020-10-15 13:44 UTC, aptiko commented on enhydris/tests/test_views.py
> +        self.assertNotContains(self.response, "message-no-data")
I like this solution, and the symmetry between the tests.

2020-10-15 13:44 UTC, aptiko commented on enhydris/tests/test_views.py
> +        )
I think these additional asserts aren't necessary, and they violate the rule that each test should test only one thing. I'd just delete them.

BTW, now would be a good time to read "Writing unit tests" in the wiki.

2020-10-19 09:17 UTC, aptiko commented
Merged in 97de984823b43cdaf3894ecc2e3f2fb9be2c1a38.

2020-10-19 09:17 UTC, closed without merging