Rewrite chart using Apex chart library
openmeteo/enhydris pull request #366
Opened 2020-11-02 09:41 UTC by eyobofficial

Closes #316

2020-11-03 12:33 UTC, aptiko commented
Thanks.

@eyobofficial Here's one problem it has. If you zoom into it, it's not granular enough—it seems to have one point every week or so. Each time you zoom in (or zoom out I guess) it should make a new request and bring in more granular data. AFAICS it doesn't make a new request on zoom in.

Now you'll notice that production has the same problem, although it *does* make a request when you zoom in. I don't know why this is. It used to work correctly in the past. I don't know when it broke, though I suspect e8a60e8.

While you take a look at this I'll add some infrastructure for linting and testing js.

2020-11-03 13:35 UTC, aptiko commented
Also the JS shouldn't be in the html, it should go in `enhydris.js`.

2020-11-05 10:42 UTC, eyobofficial commented
> Also the JS shouldn't be in the html, it should go in `enhydris.js`.

The problem with moving the code to a dedicated JS file is it would be impossible (as far as I know) to dynamically build the API URL for the current page. Is there any technic I am missing that can be used to solve that in a JS file?

```
  const config = {
    blue: "#008FFB",
    gray: "#546E7A",
    api: "{% url 'timeseries-chart' station_id=object.gentity.id timeseries_group_id=object.id pk=object.default_timeseries.id %}"
  };
```

2020-11-05 11:00 UTC, aptiko commented
Yes, we have this in `templates/enhydris/base/default.html` (which is the main template):
```
      <script>
        var enhydris = {};
        enhydris.staticUrl = '{% static "" %}';
        enhydris.rootUrl = '{% url "station_list" %}';
      </script>
      <script src="{% static 'js/enhydris.js' %}"></script>
```
So you can add more variables there.

2020-11-06 09:20 UTC, eyobofficial commented
> Thanks.
> 
> @eyobofficial Here's one problem it has. If you zoom into it, it's not granular enough—it seems to have one point every week or so. Each time you zoom in (or zoom out I guess) it should make a new request and bring in more granular data. AFAICS it doesn't make a new request on zoom in.
> 
> Now you'll notice that production has the same problem, although it _does_ make a request when you zoom in. I don't know why this is. It used to work correctly in the past. I don't know when it broke, though I suspect [e8a60e8](https://github.com/openmeteo/enhydris/commit/e8a60e8b0634cbc0c52aed27f8e5a5756dfc5097).
> 
> While you take a look at this I'll add some infrastructure for linting and testing js.

It seems to me all the points are getting plotted to the chart during the initial load. The poins are retrieved using the [charts endpoint](https://openmeteo.org/api/stations/1403/timeseriesgroups/476/timeseries/9505/chart/) that looks like it's returning all the associated timeseries values. Thus, when zooming in, there are no more granular data to retrieve that have not been already plotted. So my question is, is there other 'hidden' in-between values that are not getting returned by above endpoint? If so, is there a separate endpoint or some kind of optional query parameters to retrieve those in-between values.

Also, I couldn't find the timeseries values in the admin page to easily change and debug them. I am currently using the django shell to work with those data and that's a bit of a slow process. Could you provide me a link to the responsible admin page? Thanks!

2020-11-06 09:31 UTC, aptiko commented
You can't download time series data from the admin page, you need to go to the time series detail page (choose CSV format). You can only upload time series data from the admin page, by supplying a file in similar format to the one you donwloaded.

For the API end point, see also https://enhydris.readthedocs.io/en/latest/dev/webservice-api.html#time-series-chart-data.

2020-11-09 11:00 UTC, aptiko requested changes

2020-11-10 20:50 UTC, eyobofficial commented on enhydris/static/js/chart.js
> +	const debounceRefetch = debounce(refetch, 200);
1. When the user selects two data points in order to zoom the chart, the built-in `fetch` function is called between these new data points (i.e. start datetime and end datetime) to retrieve more granular timeseries data and populate them on the chart. The `refetch` function encapsulates this functionality. To make this more clear, I have now changed the function name to `refetchChart`.

2. The way the `selection` event of the apex chart works is -- as soon as the user starts the selection process, the event is executed multiple times for each mouse drag. Since the `refetchChart` method is called by this event (and since the `refetchChart` method makes API calls to retrieve granular chart data), multiple API calls are made before the user is done selecting. To mitigate this, the `debounce` function takes a callable and returns another modified callable that is only executed after a certain amount of time. This way the generated callable from the `debounce` function gives the user a certain amount time (200 milliseconds in this case) before firing the `selection` event. You can checkout [this](https://www.freecodecamp.org/news/debounce-explained-how-to-make-your-javascript-wait-for-your-user-to-finish-typing-2/) and [this](https://gist.github.com/nmsdvid/8807205) links to read more about this pattern.

While the `debounce` function name is confusing, I avoided using another name as it is a commonly used name for this pattern in the JavaScript community and this might come handy in the future when looking to debug it. However, if you still think it's still better to rename it to something more fitting to our case, please let me know and I will quickly change it. 

**Note:** I have made some little modifications to the `debounce` function to make it ES6 compliant.

2020-11-10 20:54 UTC, eyobofficial commented on enhydris/static/js/chart.js
> +	const optionsLine = {
Instead of `largeChart` and `smallChart`, I now used  `mainChart` and `miniChart`. I felt that is more suitable for the case. But if you still think that the 'small' and 'large' combination is better, please let me know and I will quickly change it.

2020-11-12 08:30 UTC, aptiko requested changes
Thanks! I think this is fine. I did make a few minor comments but this is because I'm very picky, it would be fine as is.

2020-11-12 08:30 UTC, aptiko commented on enhydris/static/js/chart.js
> +	// Global configuration values
I think this comment isn't needed, things are clear enough.

2020-11-12 08:30 UTC, aptiko commented on enhydris/static/js/chart.js
> +	// Main ("big") chart
I think that "main chart" and "mini chart" are clear names, so this comment isn't needed.

2020-11-12 08:30 UTC, aptiko commented on enhydris/static/js/chart.js
> +	// Mini ("small") chart
Likewise for this comment.

2020-11-12 08:30 UTC, aptiko commented on enhydris/static/js/chart.js
> +	// Make API call
I think this comment isn't useful, it's pretty much clear that `fetch(enhydris.chartApiUrl)` is making an API call.

2020-11-12 08:30 UTC, aptiko commented on enhydris/templates/enhydris/timeseries_group_detail/main-default.html
> +  {# Only load Apex library & JavaScript code if chart data exists #}
I think that this comment and the `{% if %}` that follows it is too much trouble for what they achieve. The JS is likely to be cached anyway, and if it isn't, it will be cached and used on a subsequent visit to another time series group, and if the user just happened to pass buy, this is his first such visit, and after finding out this time series group has no data he leaves and never comes back, well, he will have wasted a little bit of bandwidth (and no time, since this will probably not delay rendering at all). But if you have a different opinion it's ok to leave it as it is.

2020-11-13 07:53 UTC, eyobofficial commented on enhydris/templates/enhydris/timeseries_group_detail/main-default.html
> +  {# Only load Apex library & JavaScript code if chart data exists #}
> I think that this comment and the `{% if %}` that follows it is too much trouble for what they achieve. The JS is likely to be cached anyway, and if it isn't, it will be cached and used on a subsequent visit to another time series group, and if the user just happened to pass buy, this is his first such visit, and after finding out this time series group has no data he leaves and never comes back, well, he will have wasted a little bit of bandwidth (and no time, since this will probably not delay rendering at all). But if you have a different opinion it's ok to leave it as it is.

I agree with the explanation. So I will make the changes accordingly.

2020-11-13 09:54 UTC, aptiko requested changes

2020-11-13 09:54 UTC, aptiko commented on enhydris/templates/enhydris/timeseries_group_detail/main-default.html
>    {% if object.default_timeseries %}
Shouldn't the `chart.js` also be loaded unconditionally?

2020-11-13 10:47 UTC, eyobofficial commented on enhydris/templates/enhydris/timeseries_group_detail/main-default.html
>    {% if object.default_timeseries %}
The `chart.js` makes an API call to the `chartApiUrl` endpoint. However, the `chartApiUrl` variable is constructed conditionally on Line 58 (otherwise constructing the URL would fail since `object.default_timeseries` is empty). Thus, if the `chart.js` is loaded without the `chartApiUrl`, the JS `fetch` function would break. This is also causing the unit tests to fail.

2020-11-13 12:58 UTC, aptiko commented on enhydris/templates/enhydris/timeseries_group_detail/main-default.html
>    {% if object.default_timeseries %}
OK, normally the template shouldn't have this kind of logic, but we'll keep it like this and fix it later. Our JS generally needs a little overhaul, so we'll proceed with setting up linting and unit testing and we'll fix it right afterwards.

2020-11-13 13:08 UTC, aptiko commented
Merged in 095f140553c5650cb8be885fbbb98c3e904232cb and ee69d07f848b855305635f90dad2f1a557997ba4.

2020-11-13 13:08 UTC, closed without merging