Implement new design for front page (#369)
openmeteo/enhydris pull request #393
Opened 2020-12-10 19:20 UTC by ad0v0

**Checklist**:

* [ ] All tests are passing
* [ ] I have added any necessary documentation and/or release notes
* [ ] I have followed the [commit message guidelines](https://wiki.antonischristofides.com/en/sops/production/development/git-and-github#committing-and-commit-messages) and the ["before submitting a pull request" guidelines](https://wiki.antonischristofides.com/en/sops/production/development/git-and-github#before-submitting-a-pull-request)
* [ ] If I introduced (or abolished) any third-party library, I will write a short paragraph in this PR [according to the guidelines](https://wiki.antonischristofides.com/sops/production/development/third-party-libraries)
* [ ] I have removed all obsoleted code

2020-12-18 14:48 UTC, ad0v0 commented
- [ ] 1. Remove the "Start of operation" from the list of stations
- [ ] 2. If the "Last update" field is empty, don't show its label at all.
- [ ] 3. The "Current sort" field doesn't seem to work here.
- [ ] 4. The station detail page has gone bad (apparently it was using the same height of map as the front page, and now that you changed the height of the map in the front page, it changed to in the station detail page).
- [ ] 5. Remove all this information from the footer. Just leave a "Powered by Enhydris"

2020-12-22 13:15 UTC, aptiko requested changes
Here's one problem:

![OnPaste 20201222-123051](https://user-images.githubusercontent.com/2692385/102878869-99e69f80-4451-11eb-97c4-4f04784b7e3e.png)

A simple solution that might work would be to make the layer switcher popup be at the front.

2020-12-22 13:15 UTC, aptiko commented on enhydris/templates/enhydris/base/search-default.html
> +    <a href="#searchtips" class="btn-searchtips" data-toggle="modal" aria-label="Show searchtips">?</a>
There are two problems here. One is minor: Instead of "search" or "list stations visible on map", please write `{% trans "search" %}` or `{% trans "list stations visible on map" %}. Django will then translate the message into whatever language is active. (If no translation exists in the active language for the message, Django will show the original message.)

The second problem is that these buttons have a fixed width. If the translation is longer they won't show right. For example, "search" is "αναζήτηση" in Greek, and "list stations visible on map" is "κατάλογος σταθμών που εμφανίζονται στο χάρτη".

2020-12-22 13:15 UTC, aptiko commented on enhydris/templates/enhydris/station_list/table.html
> +      <h2 class="reset-text">Search query name</h2>
What are these messages? I don't understand their purpose.

2020-12-24 12:21 UTC, ad0v0 commented on enhydris/static/images/icon-arrow-down-full.svg
> +</svg>
- unicode is a code that uses pixels for displaying as all characters
-  svg is an image that would look good on all kinds of screens (as it displayes as non separating line without pixels) 

Actually, I even haven't thought about using unicode, as arrows etc are considered as an icon and it's a good practise in a front end world to use such images in svg format

2020-12-24 12:23 UTC, ad0v0 commented
> https://github.com/openmeteo/enhydris/pull/393#pullrequestreview-556982336

By front you mean in the front of search block?

2020-12-24 12:28 UTC, ad0v0 commented on enhydris/static/images/icon-mail.svg
> +</svg>
Those images are used when we have a full footer that created designer. If I delete those images then most likely they won't be displayed when we have a full footer.  Unless you've already saved them and added somewhere where they should have been placed in the first place. I don't know where is that so I've added them on the current  repo and banch 😅

2020-12-24 12:29 UTC, ad0v0 commented on enhydris/static/images/icon-github.svg
> +</svg>
https://github.com/openmeteo/enhydris/pull/393#discussion_r548516221

2020-12-24 12:29 UTC, ad0v0 commented on enhydris/static/images/icon-arrow-down.svg
> +</svg>
https://github.com/openmeteo/enhydris/pull/393#discussion_r548514459

2020-12-24 12:30 UTC, ad0v0 commented on enhydris/static/images/logo-lubeck.svg
> +<svg width="64" height="22" viewBox="0 0 64 22" fill="none" xmlns="http://www.w3.org/2000/svg">
As for the image, I've used what I had in the design

2020-12-24 12:45 UTC, ad0v0 commented on enhydris/templates/enhydris/base/default.html
> +      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap" rel="stylesheet">
Actually, I was planning to ask if we could still use this font but instead of loading it from any external resources, serve them as files from our service. Moreover it's also considered as a good practise as we can improve page loading performance by optimizing font loading and rendering

This is where we can take the files: https://google-webfonts-helper.herokuapp.com/fonts/noto-sans?subsets=latin

Adn yes, this font actually looks okay, as it considered to be designed specifically for multilanguage websites http://prntscr.com/w94owd | https://fonts.google.com/specimen/Noto+Sans#glyphs

I don't know if this font is an important part of the design, but don't think there's going to be any issues with it - see above. But if you actually face any issues, you can always delete this line `font-family: "Noto Sans", "Arial", sans-serif;` in enhydris.css file http://prntscr.com/w94ulv. And after that everything will get back to Bootstrap default font

2020-12-24 12:55 UTC, ad0v0 commented on enhydris/templates/enhydris/base/default.html
> +  <body{% if 'enhydris' in request.path %} class="page page-map-full"
I've used this condition in order to be able to implement different footer and show it separately (not to apply each three different styling  on one page). So:
- enhydris or the most main part in the portal (If I understood you correctly in Slack) will have the full footer with all social links etc
- openmeteo will have only "Powere by"
- and the page with station details had some issues with the layout, as it had some conflicts with an old styling

I'm not sure how it should be done properly in Django , so I've found the easist solution that I could understand how to implement without bothering anyone on the team. So, now you can implement the correct solution in Django, the only thing you will need is to apply different classe to body tag depending on the page that is loaded. Maybe it could be done some other way, I don't know. In any case, all required HTML code and CSS styling is in the project and ready to be used as you need

2020-12-24 13:09 UTC, ad0v0 commented on enhydris/templates/enhydris/base/default.html
> +        var enhydris = {};
I don't remember making such changes . And I'm not sure when and how that happend. Tried to see in which commit it was done, but I've tried to figure out where the change was made and found the following commits:
- https://github.com/ad0v0/enhydris/commit/94612573ada04ff9f2f65814cbf43c80d65c2a68#diff-c111e5a8723ca4a868de5d692946722068b9b06ea7d07d17e96c0e93e5de15c8 var is used
- https://github.com/ad0v0/enhydris/commit/f68cb1189e9dfb910e35923ec980c9ce4b0d779d#diff-c111e5a8723ca4a868de5d692946722068b9b06ea7d07d17e96c0e93e5de15c8 changed to const

Do you know what could lead to changing it back?

2020-12-24 13:15 UTC, ad0v0 commented on enhydris/templates/enhydris/base/footer-default.html
> +{%  if 'enhydris' in request.path %}
Yep, I'm totally lost here . Is this something you'll be able to fix yourself? Because I'm not sure how otherwise I should share the implementation of the redesigned footer in two different versions 😅

2020-12-24 13:21 UTC, ad0v0 commented on enhydris/templates/enhydris/station_list/table.html
> +      <h2 class="reset-text">Search query name</h2>
Me neither :)
It was in the design: http://prntscr.com/w95on6

2020-12-24 13:21 UTC, ad0v0 commented on enhydris/templates/enhydris/station_list/table.html
> +      <h2 class="reset-text">Search query name</h2>
So I've implemented it

2020-12-24 14:23 UTC, ad0v0 commented on enhydris/templates/enhydris/base/search-default.html
> +    <a href="#searchtips" class="btn-searchtips" data-toggle="modal" aria-label="Show searchtips">?</a>
Done ✔️ 

I've chose `{% trans "list stations visible on map" %}`, as there's already "search" button on the page http://prntscr.com/w97333

2020-12-25 18:21 UTC, ad0v0 commented
> By front you mean in the front of search block?

I've changed the position of the map tool, so the tool popup would not show upfront or below any other content on the page

2020-12-25 18:21 UTC, ad0v0 commented
Feedback implemented 👌

2020-12-29 09:40 UTC, aptiko commented
Hi,

I don't find new layer switcher's position satisfactory. Now in large widths the layer switcher's placement appears odd, whereas in very small widths we have the same problem we had before. Is it possible to leave it where it was, but change the z-indexes so that the layer switcher's pop-up menu is in the front of the various fields and buttons we have there?

Regarding the button sizes, is it possible to make them automatically become as wide as needed in order to accommodate the text? I think that when the text changes to "κατάλογος σταθμών που εμφανίζονται στο χάρτη", it would be better for the button to become wider than for the text to wrap.

2021-01-04 10:33 UTC, aptiko commented
Merged in 9f302077c21611ce300c932e9b1399c8d7b01e67.

To answer your question about empty vs. full footer: think of Enhydris (with the empty footer) as Wordpress, and think of the full footer as a Wordpress theme. Here we just need to define the empty footer. We don't need to add any provision as to what the "full" footer will contain. The person who creates the "theme" will care about that and store any needed redefined blocks and icons in the "theme", which is in another repository.

I made many fixes in the commit following the above. If you are curious, I can answer any other questions you have.

2021-01-04 10:33 UTC, closed without merging