fixed invalid url old timerseries
openmeteo/enhydris pull request #494
Opened 2023-05-19 15:11 UTC by Shrhawk

**Checklist**:

* [ ] All tests are passing
* [ ] I have added any necessary documentation and/or release notes
* [ ] I have followed the [commit message guidelines](https://wiki.antonischristofides.com/en/sops/production/development/git-and-github#committing-and-commit-messages) and the ["before submitting a pull request" guidelines](https://wiki.antonischristofides.com/en/sops/production/development/git-and-github#before-submitting-a-pull-request)
* [ ] If I introduced (or abolished) any third-party library, I will write a short paragraph in this PR [according to the guidelines](https://wiki.antonischristofides.com/sops/production/development/third-party-libraries)
* [ ] I have removed all obsoleted code

2023-05-19 15:11 UTC, Shrhawk commented
https://github.com/openmeteo/enhydris/issues/493

2023-05-22 18:16 UTC, aptiko requested changes
1. The commit message needs proper capitalization and spelling, and should also be in the imperative. It should also have `(fixes #493)` in the end. (See also "Git and GitHub" [section "Commit and commit messages"] in Confluence.)
2. I found out that this problem also occurs in the new URLs after all, not only in the deprecated; for example, under `/api/stations/2012/timeseriesgroups/584/timeseries/{hello}/data/`. This means the commit message should not mention the "old" URL. It could be, for example, `Fix crash in invalid timeseries URL (fixes #493)`.

2023-05-22 18:16 UTC, aptiko commented on enhydris/api/views.py
> +        ts = get_object_or_404(models.Timeseries, pk=int(pk))
Was this working before? If yes, why is this change needed? (And how on earth was it working?)

2023-05-22 18:16 UTC, aptiko commented on enhydris/api/views.py
> +        timeseries = get_object_or_404(models.Timeseries, pk=int(pk))
Same question.

2023-05-22 18:16 UTC, aptiko commented on enhydris/api/views.py
> +    lookup_value_regex = '\d+'
If this line is added, then I can't reproduce the problem any more. If that is the case, why do we have the `try...except` in `_get_data()`?

2023-05-23 08:00 UTC, Shrhawk commented on enhydris/api/views.py
> +        ts = get_object_or_404(models.Timeseries, pk=int(pk))
Yes @aptiko it was working fine, just make it consistent for the views

2023-05-23 10:20 UTC, Shrhawk commented on enhydris/api/views.py
> +    lookup_value_regex = '\d+'
@aptiko added try catch at `_get_data()` here bcz it's not the direct part of view, can be called anywhere from the code

2023-05-23 12:15 UTC, Shrhawk commented
Closed in favor of https://github.com/openmeteo/enhydris/pull/495 (renamed the branch)

2023-05-23 12:15 UTC, closed without merging