fix delete station (fixes #492)
openmeteo/enhydris pull request #496
Opened 2023-05-25 06:00 UTC by Shrhawk

**Checklist**:

* [ ] All tests are passing
* [ ] I have added any necessary documentation and/or release notes
* [ ] I have followed the [commit message guidelines](https://wiki.antonischristofides.com/en/sops/production/development/git-and-github#committing-and-commit-messages) and the ["before submitting a pull request" guidelines](https://wiki.antonischristofides.com/en/sops/production/development/git-and-github#before-submitting-a-pull-request)
* [ ] If I introduced (or abolished) any third-party library, I will write a short paragraph in this PR [according to the guidelines](https://wiki.antonischristofides.com/sops/production/development/third-party-libraries)
* [ ] I have removed all obsoleted code

2023-05-25 06:01 UTC, Shrhawk commented
Related pull request https://github.com/openmeteo/enhydris-synoptic/pull/81

2023-05-30 18:53 UTC, aptiko requested changes
Please also properly capitalize the commit message.

2023-05-30 18:53 UTC, aptiko commented on enhydris/models/timeseries_group.py
> +    gentity = models.ForeignKey(Gentity, on_delete=models.SET_NULL, null=True)
This isn't right. All `TimeseriesGroup` objects should have a related `gentity`, it can't be null. I believe that if you search the Django documentation or the web (or if you ask ChatGPT) you'll find a way for admin to not warn you about the deletion of related objects. It is this warning that causes the problem, because it can be huge and it takes a large amount of time to prepare it.

2023-05-31 13:46 UTC, Shrhawk commented on enhydris/models/timeseries_group.py
> +    gentity = models.ForeignKey(Gentity, on_delete=models.SET_NULL, null=True)
@aptiko please review now

2023-06-01 16:44 UTC, aptiko requested changes

2023-06-01 16:44 UTC, aptiko commented on enhydris/admin/station.py
> +    actions = None
Why `actions = None`?

2023-06-01 16:44 UTC, aptiko commented on enhydris/admin/station.py
> +        return self.response_delete(request, obj_display, object_id)
The problem with this is that it will not show a confirmation at all. We do want a confirmation, but we don't want it to show the related objects.

You may want to look at [Django ticket 10919](https://code.djangoproject.com/ticket/10919) to see how other people have worked around this problem.

2023-06-02 09:18 UTC, Shrhawk commented on enhydris/admin/station.py
> +    actions = None
Skipping the bulk delete here, do we need this @aptiko ?

2023-06-02 10:35 UTC, Shrhawk commented on enhydris/admin/station.py
> +        return self.response_delete(request, obj_display, object_id)
<img width="1268" alt="Screenshot 2023-06-02 at 3 27 19 PM" src="https://github.com/openmeteo/enhydris/assets/7054417/545d5132-b52e-47ee-9dd0-c3bcfb307ff8">

@aptiko this looks good to you now ?

2023-06-02 16:45 UTC, aptiko commented on enhydris/admin/station.py
> +        return self.response_delete(request, obj_display, object_id)
It's still a problem, because it gives to the user the impression that there are no related objects. So the user might think "OK, this station has nothing in it, no problem if I delete it."

So after the "are you sure?" question, it should say that "All objects related to the station, including images, events and time series, will also be deleted."

2023-06-05 06:04 UTC, merged